### PR TITLE
examples: fix typo in mobilenet examples

### PR DESCRIPTION
**Pull request by utkobe**
There is a typo in the image classification example: mobileNet => mobilenet. @yorkie @wordcount Please help me have a review on this

### CODE REVIEW

**Comment by yorkie** [comment]
That might not be a typo, https://github.com/alibaba/pipcook/tree/master/packages/pipcook-plugins-local-mobileNet-model-load, it's in "mobileNet" at GitHub :)

**Comment by utkobe** [comment]
@yorkie the npm package name in that one is lowercase 
 https://github.com/alibaba/pipcook/blob/master/packages/pipcook-plugins-local-mobileNet-model-load/package.json
Probably I also need to change the name of the folder

**Comment by yorkie** [comment]
Got it, you can try it, but I remember that the git is case-insensitive :(

**Comment by yorkie** [comment]
> [CLA assistant check](https://cla-assistant.io/alibaba/pipcook?pullRequest=24)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/pipcook?pullRequest=24) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/pipcook?pullRequest=24) it.

@utkobe Sign this, too :)

**Comment by utkobe** [comment]
> Got it, you can try it, but I remember that the git is case-insensitive :(

Exactly, but the package is case-insensitive. If i import package with uppercase in codes, it will throw errors ~

**Comment by utkobe** [comment]
So i suggest it's not necessary to change folder name in git. But need to change this in the codes . Thus i will not modify further in this commit for now 😊

**Comment by yorkie** [comment]
> So i suggest it's not necessary to change folder name in git. But need to change this in the codes . Thus i will not modify further in this commit for now 😊

@utkobe May I ask you to try to remove the folder and then add it in the new(lower-case) name in 2 commits? It actually does make a mess with the inconsistent name.

**Comment by utkobe** [comment]
> > So i suggest it's not necessary to change folder name in git. But need to change this in the codes . Thus i will not modify further in this commit for now 😊
> 
> @utkobe May I ask you to try to remove the folder and then add it in the new(lower-case) name in 2 commits? It actually does make a mess with the inconsistent name.

Sure, have done it

**Pull request merged**
