### PR TITLE
costa: refactor unit test with ava

### PR DESCRIPTION
**Pull request by FeelyChau**
Unit test for:

- [x] runnable
- ~~runtime @rickycao-qy~~
- [x] entry
- [x] ipc/ipc-proxy
- [x] ipc/parent

### CODE REVIEW

**Comment by FeelyChau** [comment]
@yorkie @WenheLI  @ LetmeBX @rickycao-qy @SirM2z May I ask you to help completing the unit tests, please?

**Comment by FeelyChau** [comment]
I have add todos to the test files, you could choose any to implement. @yorkie @WenheLI @LetmeBX @rickycao-qy @SirM2z

**Comment by rickycao-qy** [comment]
@FeelyChau This work looks interesting. Could you assign some of the parts to me accordingly?

**Comment by FeelyChau** [comment]
> @FeelyChau This work looks interesting. Could you assign some of the parts to me accordingly?

So nice of you, could you help to complete the tests of `runtime`?

**Comment by rickycao-qy** [comment]
> > @FeelyChau This work looks interesting. Could you assign some of the parts to me accordingly?
> 
> So nice of you, could you help to complete the tests of `runtime`?

sounds good

**Comment by FeelyChau** [comment]
We will add unit tests for runtime later.

**Review by rickycao-qy — APPROVED** [review]
LGTM

**Review by WenheLI — APPROVED** [review]
LGTM

**Review by yorkie — APPROVED** [review]

**Pull request merged**
