### PR TITLE
boa: fix import { X } from Y

### PR DESCRIPTION
**Pull request by FeelyChau**
fix issue: https://github.com/alibaba/pipcook/issues/170
```js
const { Image } = boa.import('PIL'); // working
const Image = boa.import('PIL.Image'); // working
const PIL = boa.import('PIL'); // working
console.log(PIL.Image); //working
```
The difference between Python and BOA implementations is:
* python
The submodule `Image` is created when module `PIL` is creating.
* boa
The module `PIL` is created, then sub module `Image` is requested, finally the `Image` is created and put into `PIL`.

### CODE REVIEW

**Comment by yorkie** [comment]
Sorry, your implementation affects all the Python objects, which is incorrect and inefficient, we only add this module check for the objects which is returned from `boa.import`.

**Comment by FeelyChau** [comment]
> Sorry, your implementation affects all the Python objects, which is incorrect and inefficient, we only add this module check for the objects which is returned from `boa.import`.

No, it has been checked by this line:
https://github.com/alibaba/pipcook/pull/300/files#diff-6f3ee49d7146f79cfafee47de76b43b4R296
only module object will enter this scope.

**Comment by yorkie** [comment]
> https://github.com/alibaba/pipcook/pull/300/files#diff-6f3ee49d7146f79cfafee47de76b43b4R296

I'm also -1 on this check here because the meaning of `PyModule_Check` does not belong to the `getItem`, and I recommend that we split the objects at the `boa.import` in JavaScript.

**Comment by FeelyChau** [comment]
> > https://github.com/alibaba/pipcook/pull/300/files#diff-6f3ee49d7146f79cfafee47de76b43b4R296
> 
> I'm also -1 on this check here because the meaning of `PyModule_Check` does not belong to the `getItem`, and I recommend that we split the objects at the `boa.import` in JavaScript.

I will perform a performance analysis on this.

Before this PR, the operator [] for module object is incorrect, it will throw an error `TypeError: 'module' object is not subscriptable`, but be caught, and we do nothing for this.

**Comment by FeelyChau** [comment]
> > > https://github.com/alibaba/pipcook/pull/300/files#diff-6f3ee49d7146f79cfafee47de76b43b4R296
> > 
> > 
> > I'm also -1 on this check here because the meaning of `PyModule_Check` does not belong to the `getItem`, and I recommend that we split the objects at the `boa.import` in JavaScript.
> 
> I will perform a performance analysis on this.
> 
> Before this PR, the operator [] for module object is incorrect, it will throw an error `TypeError: 'module' object is not subscriptable`, but be caught, and we do nothing for this.

Well, we just caught this error and print to debug, it will hidden the error information.
https://github.com/alibaba/pipcook/blob/master/packages/boa/lib/index.js#L377

I read the spec for import, the submodule won't be loaded automatically unless explicitly declared in `__init__.py`, so this implementation is not  incorrect.
I'll take a look at it again.

**Comment by yorkie** [comment]
> I read the spec for import, the submodule won't be loaded automatically unless explicitly declared in __init__.py, so this implementation is not incorrect.

Why does Boa need to take care about the `__init__.py`? Python's import function will handle this.

**Comment by FeelyChau** [comment]
> > I read the spec for import, the submodule won't be loaded automatically unless explicitly declared in **init**.py, so this implementation is not incorrect.
> 
> Why does Boa need to take care about the `__init__.py`? Python's import function will handle this.

Yeah, this is what I mean, it's another case. The point is, the following code is incorrect in cpython:
```python
import PIL
print(PIL.Image) # throw Error
```
let's go back to the node:
```js
/* case 1*/
const { Image } = boa.import('PIL'); // should work

/* case 2 */
const PIL = boa.import('PIL');
console.log(PIL.Image); // should throw error or get undefined
```
* case 1:
node import requires 2 step:
1. construct the import module (`PIL`)
2. destruct module object `PIL`, get sumodule `Image`
* case 2:
we get `PIL.Image` by 2 step too:
1. construct the import module (`PIL`)
2. get submodule `Image` by getter of `PIL`

Deconstruction is actually done through getter, so we can't distinguish between the two cases, so we can't expect the same code to behave the same in node environment.

**Comment by yorkie** [comment]
I think the key problem is to split the import-clause with the dot-clause, however it seems that not supported at Node.js/v8.

**Comment by FeelyChau** [comment]
I think this PR should be closed for now.

**Pull request closed without merging**
