### PR TITLE
fix data batch

### PR DESCRIPTION
**Pull request by rickycao-qy**
There is bug in dataloader:
  the fetchIndex (pointer to current data) is not updated

### CODE REVIEW

**Review by yorkie — DISMISSED** [review]
LGTM

**Comment by yorkie** [comment]
And removed the label `bug` which is for issue-only.

**Comment by FeelyChau** [comment]
> And removed the label `bug` which is for issue-only.

Maybe we should create a new label `bug-fix`.

**Comment by yorkie** [comment]
> > And removed the label `bug` which is for issue-only.
> 
> Maybe we should create a new label `bug-fix`.

Why do we need this label?

**Review by WenheLI — APPROVED** [review]
LGTM

**Pull request merged**
