### PR TITLE
ci: retry when failed

### PR DESCRIPTION
**Pull request by FeelyChau**

### CODE REVIEW

**Comment by yorkie** [comment]
Retries on CI is not enough that in our use case, we should confirm this mechanism is also applied to install plugins specifically.

**Comment by FeelyChau** [comment]
> Retries on CI is not enough that in our use case, we should confirm this mechanism is also applied to install plugins specifically.

Yes, this is what the issue #442 wants to do, before the installation-retry mechanism implement, we could add the action-retry-plugin to avoid too much human intervention because of network.

**Comment by yorkie** [comment]
No, #442 is not to add retry to CI and not fix the CI problems :(

**Comment by FeelyChau** [comment]
> No, #442 is not to add retry to CI and not fix the CI problems :(

What I mean `this` is what you want to do.
```
we should confirm this mechanism is also applied to install plugins specifically.
```

**Pull request closed without merging**
