### PR TITLE
sdk: fix pipeline update params

### PR DESCRIPTION
**Pull request by FeelyChau**

### CODE REVIEW

**Comment by yorkie** [comment]
Why not change the test case's config?

**Comment by yorkie** [comment]
And is this a breaking change?

**Comment by FeelyChau** [comment]
> Why not change the test case's config?

Updated.

**Comment by FeelyChau** [comment]
> And is this a breaking change?

The parameter config was used as type `PipelineConfig`, so this PR will not change the user cases.

**Review by yorkie — APPROVED** [review]

**Pull request merged**
