### PR TITLE
doc: add `pipcook.params` in spec documentation

### PR DESCRIPTION
**Pull request by yorkie**
I will update to Chinese version when the English LGTY :)

### CODE REVIEW

**Comment by yorkie** [comment]
Ping @WenheLI @FeelyChau

**Comment by FeelyChau** [comment]
How could I define a `string`/`number` type with options? I think it is common.
Does this work?
```json
{
  "name": "log-level",
  "type": "string",
  "options": [
    "debug",
    "info",
    "warn",
    "error"
  ],
  "defaultValue": "error",
  "description": "log level value"
}
```

**Comment by yorkie** [comment]
> How could I define a `string`/`number` type with options? I think it is common.
> Does this work?
> 
> ```json
> {
>   "name": "log-level",
>   "type": "string",
>   "options": [
>     "debug",
>     "info",
>     "warn",
>     "error"
>   ],
>   "defaultValue": "error",
>   "description": "log level value"
> }
> ```

The option doesn't work with literal type, because it could be rendered in text input only, and some parameter with option is expected to be a `<select />`.

**Comment by yorkie** [comment]
The correct way is to use the type `string[1]`.

**Comment by yorkie** [comment]
Any ideas? @FeelyChau @WenheLI @rickycao-qy

**Comment by WenheLI** [comment]
> > How could I define a `string`/`number` type with options? I think it is common.
> > Does this work?
> > ```json
> > {
> >   "name": "log-level",
> >   "type": "string",
> >   "options": [
> >     "debug",
> >     "info",
> >     "warn",
> >     "error"
> >   ],
> >   "defaultValue": "error",
> >   "description": "log level value"
> > }
> > ```
> 
> The option doesn't work with literal type, because it could be rendered in text input only, and some parameter with option is expected to be a `<select />`.



@yorkie I am confused here. Why we should use `string[1]` in the above example, as the `log-level` is just a single `string` (Why use an array?

**Comment by yorkie** [comment]
> @yorkie I am confused here. Why we should use string[1] in the above example, as the log-level is just a single string (Why use an array?

As I mentioned before, the string is a literal type that will not have the options and the string array will have the `options` to be configured to a <select />.

**Review by WenheLI — APPROVED** [review]
LGTM

**Review by rickycao-qy — APPROVED** [review]
LGTM

**Review by FeelyChau — APPROVED** [review]
LGTM.

**Pull request merged**
