### PR TITLE
boa, build: add ppc64le support for powerci

### PR DESCRIPTION
**Pull request by yorkie**

### CODE REVIEW

**Comment by yorkie** [comment]
As a new CI on PowerCI(by [oregonstate.edu](https://oregonstate.edu/)) is setup: https://powerci.osuosl.org/job/pipcook-ppc64le-linux/, we have to support ppc64le for building and running pipeline.

**Comment by yorkie** [comment]
@FeelyChau could you please have a look at https://powerci.osuosl.org/job/pipcook-ppc64le-linux/20/console, it seems failed by a plugin installation error.

**Comment by yorkie** [comment]
> @FeelyChau could you please have a look at https://powerci.osuosl.org/job/pipcook-ppc64le-linux/20/console, it seems failed by a plugin installation error.

The same problem is found here: https://stackoverflow.com/questions/60825109/tensorflow-installation-fails-on-powerpc-ppc64le, which is caused by no suitable tensorflow package for ppc64le, we might need to change to use conda instead `venv` to support Pipcook on this type of machine.

**Comment by FeelyChau** [comment]
> > @FeelyChau could you please have a look at https://powerci.osuosl.org/job/pipcook-ppc64le-linux/20/console, it seems failed by a plugin installation error.
> 
> The same problem is found here: https://stackoverflow.com/questions/60825109/tensorflow-installation-fails-on-powerpc-ppc64le, which is caused by no suitable tensorflow package for ppc64le, we might need to change to use conda instead `venv` to support Pipcook on this type of machine.

It seems that miniconda can solve this problem, I'll check this.

**Review by FeelyChau — APPROVED** [review]
We will fix the run error later.

**Pull request merged**
