### PR TITLE
cli: add command "plugin info"

### PR DESCRIPTION
**Pull request by FeelyChau**

### CODE REVIEW

**Comment by yorkie** [comment]
@FeelyChau could you please explain why do we add this?

**Comment by FeelyChau** [comment]
User couldn't fetch the plugin detail.

**Comment by yorkie** [comment]
The plugin info is just the plugin's `package.json`, which they could found from the source.

**Comment by FeelyChau** [comment]
> The plugin info is just the plugin's `package.json`, which they could found from the source.

It's incomplete, what we also need: installing time, where the plugin come from, error message if failed, they can't be fetched from package meta.

**Comment by yorkie** [comment]
Reasonable, and the documentation is also needed :)

**Review by yorkie — APPROVED** [review]

**Review by yorkie — APPROVED** [review]

**Pull request merged**
