### PR TITLE
upgrade docker file to version 1.1

### PR DESCRIPTION
**Pull request by wordcount**
update Dockerfile，use nodejs-12 as base

### CODE REVIEW

**Comment by rickycao-qy** [comment]
LGTM

**Comment by wordcount** [comment]
> May I ask you to not change the Dockerfile path? This is broken with https://github.com/alibaba/pipcook/blob/master/docs/INSTALL.md#install-via-docker.

Normally docker will add all file as it's build context, this will add build time and may cause other problems.
>[reference of docker build command](https://docs.docker.com/engine/reference/commandline/build/)
In most cases, it’s best to put each Dockerfile in an empty directory. Then, add to that directory only the files needed for building the Dockerfile.

**Comment by yorkie** [comment]
Reasonable @wordcount, May I ask you to update the documentation, too?

**Comment by wordcount** [comment]
> Reasonable @wordcount, May I ask you to update the documentation, too?

done

**Comment by wordcount** [comment]
> LGTM even though the markdown links might be 404.

where

**Pull request merged**
