### PR TITLE
costa: support multi version of plugins

### PR DESCRIPTION
**Pull request by FeelyChau**
1. support multi version of plugins.
2. use `pnpm` instead of `npm`.

todo list:

* unit tests need to be added.
* script init-dev should be updated.
* boa should be installed into pnpm cache.
* benchmark.

### CODE REVIEW

**Comment by yorkie** [comment]
What about the cnpm?

**Comment by FeelyChau** [comment]
> What about the cnpm?

[The `alias` installation is not done for npmInstall](https://github.com/cnpm/npminstall/pull/327), we could make benchmark if it's done .

**Comment by yorkie** [comment]
Because we are always using NPM for plugin installation, so we don't consider the CNPM.

**Comment by FeelyChau** [comment]
Supporting multi versions for plugin need to refactor the database and costa runtime,  it looks like a lot of work, and we can do it in version 2.0.

**Pull request closed without merging**
