### PR TITLE
costa: add python runnable for machine-learning developers

### PR DESCRIPTION
**Pull request by yorkie**
In order to better attract machine learning developers to contribute models to Pipcook, this PR provides developers with a native Python development environment. For users who do not use Node.js and JavaScript, they can use pure Python to write plugins.

### CODE REVIEW

**Comment by yorkie** [comment]
Tests and documentation are still working in progress :)

**Comment by rickycao-qy** [comment]
To get this working, Boa needs to support pass Javascript (class, function, etc.) to Python and executed in Python. Otherwise, this will not work.

**Comment by yorkie** [comment]
@rickycao-qy Which case do we need to pass a function/class to Python?

**Comment by yorkie** [comment]
@rickycao-qy I have updated the tests for using JavaScript functions in Python env at packages/costa/test/plugins/python-simple/__init__.py, the only problem is that the Python objects from JavaScript are a dictionary so that:

```py
def main(input):
  input.get('fn1')() # working
  input.fn1() # not working
```

I will open another PR to change to case 2.

**Comment by yorkie** [comment]
@rickycao-qy I have supported access to the object attributes in dot notation(#389), I will switch to dot when it gets merged like:

```py
def main(input):
  input.fn1()
```

**Comment by yorkie** [comment]
@rickycao-qy @FeelyChau I have rebased this pull request :)

**Comment by rickycao-qy** [comment]
LGTM

**Pull request merged**
