### PR TITLE
boa: add magic methods on Python objects

### PR DESCRIPTION
**Pull request by yorkie**

### CODE REVIEW

**Comment by yorkie** [comment]
The tests are added, @FeelyChau could you please help me review this?

**Comment by WenheLI** [comment]
Seems like CI fail due to `##[error]  367:15  error  Unexpected parentheses around single function argument  arrow-parens
`
Try to remove the parentheses?

**Comment by yorkie** [comment]
> Seems like CI fail due to `##[error] 367:15 error Unexpected parentheses around single function argument arrow-parens `
> Try to remove the parentheses?

Updated, thank you @WenheLI!

**Review by FeelyChau — APPROVED** [review]
LGTM.

**Review by WenheLI — APPROVED** [review]
LGTM

**Pull request merged**
