### PR TITLE
cli: optimize npm client config.

### PR DESCRIPTION
**Pull request by Txiaozhe**

### CODE REVIEW

**Comment by yorkie** [comment]
And @Txiaozhe please sign the CLA again.

**Comment by Txiaozhe** [comment]
> And @Txiaozhe please sign the CLA again.

I do it, is it ok?

**Comment by yorkie** [comment]
Still pending. @Txiaozhe

**Comment by Txiaozhe** [comment]
It is not passed because I use a new mac, and I have retried it.

**Pull request closed without merging**
